### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '7.'

### ISSUE THREAD

**Issue by shixudongleo** [soravux/scoop#33]
I encounter an error while using scoop:
How to slove it?

I am using: 
Python 2.7.5
scoop (0.7.1.1)

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/s/shixudon/.local/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/home/s/shixudon/.local/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/home/s/shixudon/.local/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 290, in run
    futures_startup()
  File "/home/s/shixudon/.local/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 271, in futures_startup
    run_name="__main__"
  File "/home/s/shixudon/.local/lib/python2.7/site-packages/scoop/futures.py", line 64, in _startup
    result = _controller.switch(rootFuture, *args, **kargs)
  File "/home/s/shixudon/.local/lib/python2.7/site-packages/scoop/_control.py", line 253, in runController
    raise future.exceptionValue
ValueError: invalid literal for int() with base 10: '7.'
```

**Comment by leconteur** [comment]
This seems to be related to a ValueError in your code. From the looks of it, you're calling int('7.') which fails because of the point. Does your code work when you do not use scoop?
