### ISSUE TITLE
TypeError: 'NoneType' object is not callable in Python 3.5

### ISSUE THREAD

**Issue by peterjpxie** [soravux/scoop#83]
Got below error when trying to run with Python 3.5 or 3.7.

cat hosts
us.mydomain.com
au.mydomain.com

root@ip-172-26-1-210:~/pythonCode# python -m scoop --hostfile hosts -n 3 --external-hostname us.petersvpn.com scoop_try.py
[2019-08-25 10:25:58,539] launcher  INFO    SCOOP 0.7 1.1 on linux using Python 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609], API: 1013
[2019-08-25 10:25:58,539] launcher  INFO    Deploying 3 worker(s) over 2 host(s).
[2019-08-25 10:25:58,539] launcher  INFO    Worker distribution:
[2019-08-25 10:25:58,539] launcher  INFO       us.mydomain.com:        1 + origin
[2019-08-25 10:25:58,540] launcher  INFO       au.mydomain.com:        1
[2019-08-25 10:26:00,978] __main__  INFO    Worker(s) launched using /bin/bash
data[0] 542, dataParallel[0] 542
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7f57f9984a70>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 105, in close
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7f57f9984ad8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 105, in close
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7f57f9984c10>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 105, in close
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
[2019-08-25 10:26:02,327] launcher  INFO    Root process is done.
[2019-08-25 10:26:00,586] __main__  INFO    Worker(s) launched using /bin/bash
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7ff077dcfc78>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 105, in close
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7ff077dcfa70>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 105, in close
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7ff077dcfb40>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 105, in close
  File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
[2019-08-25 10:26:04,841] launcher  INFO    Finished cleaning spawned subprocesses.

**Comment by blooop** [comment]
I get the same errors in python 2.7

**Comment by MichaelClerx** [comment]
Seeing something similar

[2019-11-06 17:12:56,929] launcher  INFO    SCOOP 0.7 1.1 on linux using Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)], API: 1013
[2019-11-06 17:12:56,929] launcher  INFO    Detected SLURM environment.
[2019-11-06 17:12:56,929] launcher  INFO    Deploying 1 worker(s) over 1 host(s).
[2019-11-06 17:12:56,929] launcher  DEBUG   Using hostname/ip: "cnode1001" as external broker reference.
[2019-11-06 17:12:56,929] launcher  DEBUG   The python executable to execute the program with is: /system/software/linux-x86_64/anaconda3/4.0.0/bin/python3.
[2019-11-06 17:12:56,930] launcher  INFO    Worker distribution:
[2019-11-06 17:12:56,930] launcher  INFO       cnode1001:       0 + origin
[2019-11-06 17:12:57,180] brokerLaunch (127.0.0.1:52951) DEBUG   Local broker launched on ports 52951, 40545.
[2019-11-06 17:12:57,181] launcher  (127.0.0.1:52951) DEBUG   Initialising local origin worker 1 [cnode1001].
[2019-11-06 17:12:57,181] launcher  (127.0.0.1:52951) DEBUG   cnode1001: Launching '(/system/software/linux-x86_64/anaconda3/4.0.0/bin/python3 -m scoop.bootstrap.__main__ --size 1 --workingDirectory /home/coml0689/dev/scoop-test --brokerHostname 127.0.0.1 --externalBrokerHostname cnode1001 --taskPort 52951 --metaPort 40545 --origin --backend=ZMQ -v script.py)'
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7feb06d07868>>
Traceback (most recent call last):
  File "/home/coml0689/.local/lib/python3.5/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/coml0689/.local/lib/python3.5/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/coml0689/.local/lib/python3.5/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
AttributeError: 'NoneType' object has no attribute 'ref'
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7feb06d07a70>>
Traceback (most recent call last):
  File "/home/coml0689/.local/lib/python3.5/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/coml0689/.local/lib/python3.5/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/coml0689/.local/lib/python3.5/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
AttributeError: 'NoneType' object has no attribute 'ref'
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7feb06d079a0>>
Traceback (most recent call last):
  File "/home/coml0689/.local/lib/python3.5/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/coml0689/.local/lib/python3.5/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/coml0689/.local/lib/python3.5/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
AttributeError: 'NoneType' object has no attribute 'ref'
[2019-11-06 17:12:58,282] launcher  (127.0.0.1:52951) INFO    Root process is done.
[2019-11-06 17:12:58,283] workerLaunch (127.0.0.1:52951) DEBUG   Closing workers on cnode1001 (1 workers).
[2019-11-06 17:12:58,283] brokerLaunch (127.0.0.1:52951) DEBUG   Closing local broker.
[2019-11-06 17:12:58,283] launcher  (127.0.0.1:52951) INFO    Finished cleaning spawned subprocesses.
