### ISSUE TITLE
Could not successfully launch the remote worker

### ISSUE THREAD

**Issue by leocus** [soravux/scoop#91]
Hello everyone!
I tried to execute the test program that you can find here (https://scoop.readthedocs.io/en/0.7/usage.html#map) by using a remote machine.

When I launch it I get: 
```
[desktop_user@localhost prove_scoop]$ python -m scoop --hostfile hostfile test.py 
[2020-06-18 21:39:14,822] launcher  INFO    SCOOP 0.7 1.1 on linux using Python 3.7.7 (default, Mar 13 2020, 10:23:39) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)], API: 1013
[2020-06-18 21:39:14,822] launcher  INFO    Deploying 2 worker(s) over 1 host(s).
[2020-06-18 21:39:14,822] launcher  INFO    Worker distribution: 
[2020-06-18 21:39:14,822] launcher  INFO       remote_user:	1 + origin
[2020-06-18 21:39:18,050] workerLaunch WARNING Could not successfully launch the remote worker on remote_user.
Requested remote group process id, received:
b''
Group id decoding error:
invalid literal for int() with base 10: ''
SSH process stderr:
b'Traceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File "/data/data/com.termux/files/usr/lib/python3.8/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scoop/bootstrap/__main__.py", line 302, in <module>\n    b.main()\n  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scoop/bootstrap/__main__.py", line 65, in main\n    os.chdir(self.args.workingDirectory)\nFileNotFoundError: [Errno 2] No such file or directory: \'/home/desktop_user/workspace/prove_scoop\'\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File "/data/data/com.termux/files/usr/lib/python3.8/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scoop/bootstrap/__main__.py", line 302, in <module>\n    b.main()\n  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scoop/bootstrap/__main__.py", line 65, in main\n    os.chdir(self.args.workingDirectory)\nFileNotFoundError: [Errno 2] No such file or directory: \'/home/desktop_user/workspace/prove_scoop\'\n'
[2020-06-18 21:39:18,051] launcher  INFO    Root process is done.
[2020-06-18 21:39:18,052] workerLaunch WARNING Zombie process(es) possibly left on host remote_user!
[2020-06-18 21:39:18,852] launcher  INFO    Finished cleaning spawned subprocesses.
```

How can I solve this?

**Comment by kukuwa** [comment]
Do you fix it?
